HMS/urls.py
"""
Definition of urls for HotelFlexProject.
"""

# Uncomment the next lines to enable the admin:
from django.urls import path, include
from django.contrib import admin, admindocs

admin.autodiscover()

urlpatterns = [
    path('', include('app.urls')),
    path('accounts/', include('signup.urls')),
    path('admin_panel/', include('admin.urls')),
    path('admin/', admin.site.urls, name='admin')
]

app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.roombooking, name='roombooking'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    # path('register/', views.SignUpView.as_view(), name='register'),
    path('booking/', views.BookingView.as_view(), name='booking'),
    path('single/', views.single, name='single'),
    path('forgotpassword/', views.forgotpassword, name='forgot'),
    path('double/', views.double, name='double'),
    path('luxury/', views.luxury, name='luxury'),
    path('deluxe/', views.deluxe, name='deluxe'),
    path('executive/', views.executive, name='executive'),
    path('presidential/', views.presidential, name='presidential'),
    path('bookinghistory/', views.bookinghistory, name='history'),
    path('test/', views.test, name='test'),
    path('rooms/', views.rooms, name='rooms'),
    path('getusers/', views.getusers, name='getusers'),
    path('available_rooms/', views.available_rooms, name='available_rooms')
]

signup/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from HMS import settings
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.WelcomeView.as_view()),
    path('register/', views.SignUpView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='signup/login.html'), name='login'),
    path('confirm/<str:uid>/<str:token>/<int:check>/', views.ConfirmEmail.as_view(), name='confirm_email'),
    path('activate/<str:uid>/<str:token>/', views.Activate.as_view(), name='activate'),
    path('logout/', LogoutView.as_view(template_name='signup/logout.html'), name='logout')
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/includes/_admin.html
{% block body %}
 <script>
     function logoutFunction() {
            window.location.reload();
        }
 </script>
<script>
    $(document).ready(function(){
        $("#booking").hover(function(){
            $(this).css("background-color", "#32CD32");
            }, function(){
        $(this).css("background-color", "#357EC7");
            });
         $("#logout").hover(function(){
            $(this).css("background-color", "#32CD32");
            }, function(){
        $(this).css("background-color", "#DC143C");
        });
    });
</script>
    <!-- Header Begin -->
    
    <!-- Header Close -->
{% endblock %}

app/templates/includes/_afterloginheader.html
{% block body %}



{% endblock %}

app/templates/includes/_footer.html
{% block body %}

<footer class="rh">
        <div class="rh-100 rh-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6 rh-f-30 rh-f-100">
                        <div class="rh-footer-box">
                            <h1>Hotel4U</h1>
                            <p>You have questions regarding our services? Contact us, we will be happy to help you out!</p>
                            <ul class="footer-about">
                                <li>iamnasir345@gmail.com</li>
                                <li>36-A Satellite Town, New Schema Bahawalpur</li>
                                <li>+92 301 7661106</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-6 rh-f-30 rh-f-50">
                        
                        <div class="rh-footer-box">
                            <h5>Hotel</h5>
                            <ul class="footer-menu list">
                                <li><a href="/">Home</a></li>
                                <li><a href="{% url 'app:about' %}">Rooms</a></li>
                                <li><a href="javascript:">Restaurant</a></li>
                                <li><a href="{% url 'app:about' %}">About us</a></li>
                                <li><a href="{% url 'app:contact' %}">Contact us</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-6 rh-f-100">
                        <div class="rh-footer-box">
                            <h5>Photo Gallery</h5>
                            <ul class="footer-menu gallery">
                                <li>
                                    <a href="{% url 'app:single' %}"><img src="../../static/app/images/footer-gallery-1.jpg" alt="footer-gallery-1" /></a>
                                </li>
                                <li>
                                    <a href="{% url 'app:single' %}"><img src="../../static/app/images/footer-gallery-2.jpg" alt="footer-gallery-2" /></a>
                                </li>
                                <li>
                                    <a href="{% url 'app:single' %}"><img src="../../static/app/images/footer-gallery-3.jpg" alt="footer-gallery-3" /></a>
                                </li>
                                <li>
                                    <a href="{% url 'app:single' %}"><img src="../../static/app/images/footer-gallery-4.jpg" alt="footer-gallery-4" /></a>
                                </li>
                                <li>
                                    <a href="{% url 'app:single' %}"><img src="../../static/app/images/footer-gallery-5.jpg" alt="footer-gallery-5" /></a>
                                </li>
                                <li>
                                    <a href="{% url 'app:single' %}"><img src="../../static/app/images/footer-gallery-6.jpg" alt="footer-gallery-6" /></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="rh footer-btm">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <h6 class="pull-left">Copyrights &copy; 2017 Hotel4U</h6>
                        <span class="pull-right">Powered by <a target="_blank" href="#">Hotel4u.com</a></span>
                    </div>
                </div>
            </div>
        </div>
</footer>

{% endblock %}

app/templates/includes/_formhelpers.html
{% macro render_field(field) %}
  {{ field.label }}
  {{ field(**kwargs)|safe }}
  {% if field.errors %}
    {% for error in field.errors %}
      <span class="help-inline">{{ error }}</span>
    {% endfor %}
  {% endif %}
{% endmacro %}

app/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}

{% if error %}
  <div class="alert alert-danger">{{error}}</div>
{% endif %}

{% if msg %}
  <div class="alert alert-success">{{msg}}</div>
{% endif %}

app/templates/includes/_navbar.html
{% block body %}
 <script>
     function logoutFunction() {
            window.location.reload();
        }
 </script>
<script>
    $(document).ready(function () {
        $("#admin").hover(function(){
            $(this).css("background-color", "#32CD32");
            }, function(){
        $(this).css("background-color", "#FF8C00");
            });
        $("#booking").hover(function(){
            $(this).css("background-color", "#32CD32");
            }, function(){
        $(this).css("background-color", "#357EC7");
            });
         $("#logout").hover(function(){
            $(this).css("background-color", "#32CD32");
            }, function(){
        $(this).css("background-color", "#DC143C");
        });
    });
</script>
    <header class="rh">
        <div class="rh-header">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-4">
                        
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-8">
                        <ul class="pull-right">
                            {% if request.user.is_authenticated %}
                            <li>
                                 <a href="{% url 'app:history' %}"> <input type="button" id ="booking" class="button" value="Booking History"></a>
                            </li>
                            <li>
                                 <a href="{% url 'accounts:logout' %}"> <input type="button" id ="logout" class="button1" value="Logout" onclick="logoutFunction()"></a>
                            </li>
                        {% else %}
                            <li>
                                 <a href="{% url 'accounts:register' %}"> <input type="button" class="button" value="Register"></a>
                            </li>
                            <li>
                                 <a href="{% url 'accounts:login' %}"> <input type="button" class="button1" value="Login"></a>
                            </li>

                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <nav class="rh navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/"><h2>Hotel4U</h2></a>
                </div>
                <div class="collapse navbar-collapse rh-toggle" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right main-navbar">  
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'app:rooms' %}">Rooms</a>
                        </li>
                        <li>
                            <a href="{% url 'app:booking' %}">Booking</a>
                        </li>
                        <li>
                            <a href="{% url 'app:about' %}">About</a>
                        </li>
                        <li>
                            <a href="{% url 'app:contact' %}">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
{% endblock %}