HMS/urls.py
"""
Definition of urls for HotelFlexProject.
"""

# Uncomment the next lines to enable the admin:
from django.urls import path, include
from django.contrib import admin, admindocs

admin.autodiscover()

urlpatterns = [
    path('', include('app.urls')),
    path('accounts/', include('signup.urls')),
    path('admin_panel/', include('admin.urls')),
    path('admin/', admin.site.urls, name='admin')
]

app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.roombooking, name='roombooking'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    # path('register/', views.SignUpView.as_view(), name='register'),
    path('booking/', views.BookingView.as_view(), name='booking'),
    path('single/', views.single, name='single'),
    path('forgotpassword/', views.forgotpassword, name='forgot'),
    path('double/', views.double, name='double'),
    path('luxury/', views.luxury, name='luxury'),
    path('deluxe/', views.deluxe, name='deluxe'),
    path('executive/', views.executive, name='executive'),
    path('presidential/', views.presidential, name='presidential'),
    path('bookinghistory/', views.bookinghistory, name='history'),
    path('test/', views.test, name='test'),
    path('rooms/', views.rooms, name='rooms'),
    path('getusers/', views.getusers, name='getusers'),
    path('available_rooms/', views.available_rooms, name='available_rooms')
]

signup/urls.py
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from HMS import settings
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.WelcomeView.as_view()),
    path('register/', views.SignUpView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='signup/login.html'), name='login'),
    path('confirm/<str:uid>/<str:token>/<int:check>/', views.ConfirmEmail.as_view(), name='confirm_email'),
    path('activate/<str:uid>/<str:token>/', views.Activate.as_view(), name='activate'),
    path('logout/', LogoutView.as_view(template_name='signup/logout.html'), name='logout')
    ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signup/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager


# Create your models here.
class CustomUser(AbstractBaseUser, PermissionsMixin):
    fullname = models.CharField(max_length=30)
    email = models.EmailField(max_length=35, unique=True)
    cell_number = models.IntegerField()
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'

    objects = UserManager()

signup/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm
import re

EMAIL_REGEX = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"
FULL_NAME_REGEX = r'^[a-zA-Z]+(([,. -][a-zA-Z ])?[a-zA-Z]*)*$'
PHONE_REGEX = r'(\+[0-9]+\s*)?(\([0-9]+\))?[\s0-9\-]+[0-9]+$'


class SignUpForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['password1'].widget.attrs['class'] = 'form-input'
        self.fields['password2'].widget.attrs['class'] = 'form-input'
        self.fields['fullname'].widget.attrs['placeholder'] = 'Full Name'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter your email'
        self.fields['cell_number'].widget.attrs['placeholder'] = 'Enter your contact Number'
        self.fields['password1'].widget.attrs['placeholder'] = 'Enter Password'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'

    class Meta:
        model = CustomUser
        fields = ['fullname', 'email', 'cell_number', 'password1', 'password2']

    def clean(self):
        return self.cleaned_data

    def clean_full_name(self):
        fullname = self.cleaned_data['full_name']
        is_valid_fullname = re.match(FULL_NAME_REGEX, fullname)
        if not is_valid_fullname or not fullname:
            raise forms.ValidationError('Enter a valid name. Number and special characters are not Allowed.')
        return fullname

    def clean_email(self):
        email = self.cleaned_data['email']
        is_valid_email = re.match(EMAIL_REGEX, email)

        if not is_valid_email or not email:
            raise forms.ValidationError("Email is invalid")
        return email

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        is_valid_phone = re.match(PHONE_REGEX, phone)
        if not is_valid_phone or not phone:
            raise forms.ValidationError("Phone number is invalid")
        return phone

    def clean_password(self):
        password = self.cleaned_data['password']
        if len(password) < 6:
            raise ValidationError("This password must contain at least 8 characters.", code='password_too_short',
                                  params={'min_length': 8}, )
        return password

signup/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.core import mail
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse
from django.contrib import messages
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import auth

from HMS import settings
from .forms import SignUpForm


# Create your views here.
from .models import CustomUser
from .token import account_activation_token


class WelcomeView(View):

    def get(self, request):
        user = request.user
        return render(request, 'base.html', {'name': user})


class SignUpView(View):

    def get(self, request):
        form = SignUpForm()
        return render(request, 'signup/signup.html', {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            subject = 'Account Activation.'
            current_site = get_current_site(request)
            uid = user.id
            token = account_activation_token.make_token(user)
            activation_link = "http://{0}/accounts/activate/{1}/{2}".format(current_site, uid, token)
            from_email = settings.EMAIL_HOST_USER
            to_email = [form.cleaned_data.get('email'), ]
            context = {'activation_link': activation_link}
            message = "Visit {}  to activate your account".format(activation_link)
            mail.send_mail(subject, message, from_email, to_email, context)
            return redirect('accounts:confirm_email', uid=uid, token=token, check=0)
        else:
            return render(request, 'signup/signup.html', {'form': form})


class ConfirmEmail(View):

    def get(self, request, uid, token, check):
        if request.user.is_authenticated:
            return redirect('/')

        new_user = CustomUser.objects.get(pk=uid)
        template = 'signup/confirm-email.html'
        context = {'user': new_user, 'uid': uid, 'token': self.kwargs['token'], 'subject': 'Account Activation'}
        return render(request, template, context)


class Activate(View):

    def get(self, request, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(self.kwargs['uid']))
            user = CustomUser.objects.get(pk=uid)
        except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
            user = None
        if user is not None and account_activation_token.check_token(user, self.kwargs['token']):
            user.is_active = True
            user.save()
            return redirect('login')
        else:
            return render_to_response('signup/invalid_link.html')

signup/templates/signup/confirm-email.html
{% extends 'base.html' %}
{% load static %}
{% block script %}
    <script>
        function ResendEmail() {
            $.ajax({
                type: "GET",
                url: '/accounts/confirm_email_retry/{{ uid }}/{{ token }}',
                success: onResend,
                dataType: 'html'
            });
        }

        function onResend() {
            $('#mailSend').css('display', 'block');
            swal("Email Resent", "Email has sent to {{ user.email }}", "success");
        }
    </script>
    <script src="{% static "register/js/sweetalert.min.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="dashboard-status-sec">
        <div class="row" style="margin: 0">
            <div class="col-md-3"></div>
            <div class="col-md-6" style="margin-top: 35px; min-height: 400px; border-top: 2px solid #3d4c95">
                <h3 class="">Confirm Your Email Address</h3><br>
                <div>
                    <p style="margin-top: 35px">
                        <b>Hi {{ user.username }},</b>
                    </p><br>
                    <p style="margin-top: 35px">Thank you! Your Information have been successfully added </p>
                        <br>
                    <p style="margin-top: 35px">
                        Kindly confirm your email <b>{{ user.email }}</b>.
                        If you have'nt receive email yet.

                    </p>
                    <div style="margin-top: 35px">
                        <button style="background: #6978bf; border: 0; margin-left: 0;" class="btn btn-primary"
                                onclick="ResendEmail()">Resend Email
                        </button>
                    </div>

                    <!-- <div style="display: none;background: lightgreen; margin-top: 30px;" id="mailSend">Email is sent to {{ user.email }}</div> -->

                </div>


            </div>
            <div class="col-md-3"></div>
        </div>

    </div>
{% endblock %}

signup/templates/signup/invalid_link.html
{% extends "base.html" %}
{% load static %}


{% block content_body %}
    <div class="main-body">
        <div class="clearfix"></div>
            <div class="container padding-bg home-banner-sec">
                <div class="col-md-6 pb-5 pt-5 center-form">
                    <div class="row">
                        <div class="col-md-12 invalid-link-page">
{#                            <img src="{% static "images/link-icon.png" %}">#}
                            <h3 class="primary-font">Invalid Activation Link!</h3>
                        </div>
                    </div>
                </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
{% endblock %}
{% block script %}
{#    <script src="{% static "js/maps.js" %}"></script>#}
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCgOL7lDzLXJ1-VMLGE11yVo4IOyGrkp-E&libraries=places&callback=initAutocomplete"
        async defer></script>
        <script type="text/javascript">
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image_preview').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }


    $(document).ready(function () {
        $("#id_avatar").change(function () {
            readURL(this)
        })
    });
    </script>
{#    <script src="{% static 'js/validators/user_profile_validator.js' %}"></script>#}
{% endblock %}

signup/templates/signup/login.html
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}" type="text/css" media="all">
    <link href="//fonts.googleapis.com/css?family=Mukta+Mahee:200,300,400,500,600,700,800" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/font-awesome.css' %}" type="text/css" media="all">
    <title>Login</title>
</head>

<body>

<h1 class="title-agile text-center"></h1>
<div class="content-w3ls">
    <div class="content-top-agile">
        <h2>Sign in to proceed</h2>

    </div>
    <div class="content-bottom">
        <form method="post">
            {% csrf_token %}
            {% if form.error %}
                <ul class="messages">
                    {{ form.error }}
                </ul>
            {% endif %}
            <div class="field-group">
                <span class="fa fa-user" aria-hidden="true"></span>
                <div class="wthree-field">
                    {{ form.username }}
                </div>
            </div>
            <div class="field-group">
                <span class="fa fa-lock" aria-hidden="true"></span>
                <div class="wthree-field">
                    {{ form.password }}
                </div>
            </div>

            <div class="wthree-field">
                <input id="saveForm" name="saveForm" type="submit" value="Log In"/>
            </div>

        </form>
        <br>

        <div style="text-align: center;">
            <a href="{% url 'app:forgot' %}" class="text-center">Forgot password?</a> &nbsp;
            <a href="{% url 'accounts:register' %}" class="text-center">Create account</a>
            <br>
        </div>

    </div>
</div>
<div class="copyright text-center">
    <p>
        © 2018 Switch Login Form. All rights reserved | Design by Nasir
    </p>
</div>
</body>

signup/templates/signup/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>logged out</title>
</head>
<body>
<h1>You have been logged in</h1>
<a href="/login/">Log in again</a>
</body>
</html>

signup/templates/signup/signup.html
{% load static %}
<head>
    <script type="application/x-javascript">
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        } </script>
    <link href="{% static 'register/css/style.css' %}" rel="stylesheet" type="text/css" media="all">
    <link href="//fonts.googleapis.com/css?family=Cuprum:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}" type="text/css" media="all">
    <link href="//fonts.googleapis.com/css?family=Mukta+Mahee:200,300,400,500,600,700,800" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'login/css/font-awesome.css' %}" type="text/css" media="all">
</head>
<body>
{% block content %}
    <div class="content-w3ls">
        <div class="content-top-agile">
            <h2>Register</h2>
        </div>
        <div class="content-bottom">
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <div class="input-error">
                        {{ form.errors }}
                    </div>
                {% endif %}
                <div class="field-group">
                    <span class="fa fa-user" aria-hidden="true"></span>
                    <div class="wthree-field">
                        <label for="Name"></label>{{ form.fullname }}
                    </div>
                </div>
                <div class="field-group">
                    <span class="fa fa-at" aria-hidden="true"></span>
                    <div class="wthree-field">
                        <label for="email"></label>{{ form.email }}
                    </div>
                </div>
                <div class="field-group">
                    <span class="fa fa-phone" aria-hidden="true"></span>
                    <div class="wthree-field">
                        <label for="Contact No."></label>{{ form.cell_number }}
                    </div>
                </div>
                <div class="field-group">
                    <span class="fa fa-lock" aria-hidden="true"></span>
                    <div class="wthree-field">
                        {{ form.password1 }}
                    </div>
                </div>
                <div class="field-group">
                    <span class="fa fa-lock" aria-hidden="true"></span>
                    <div class="wthree-field">
                        {{ form.password2 }}
                    </div>
                </div>
                <div class="wthree-field">
                    <input id="saveForm" name="saveForm" type="submit" value="Register"/>
                </div>
                <div class="wthree-field">
                    <a href="/">Go to home</a>
                </div>
            </form>
        </div>
    </div>
    <div class="footer-w3l">
        <p>&copy; 2020 Classy Register Form. All rights reserved | Design by <a
                href="#">Nasir</a></p>
    </div>
    <script type="application/x-javascript"> addEventListener("load", function () {
        setTimeout(hideURLbar, 0);
    }, false);

    function hideURLbar() {
        window.scrollTo(0, 1);
    } </script>
    <script type="text/javascript" src="{% static 'register/js/jquery-2.1.4.min.js' %}"></script>
    <script>$(document).ready(function (c) {
        $('.alert-close').on('click', function (c) {
            $('.main-agile').fadeOut('slow', function (c) {
                $('.main-agile').remove();
            });
        });
    });</script>
{% endblock %}
</body>

signup/templates/signup/user-already-exists.html
{% extends 'base.html' %}
{% load static %}
{% block content_body %}
     <title>Welcome to Online Marriage Booking</title>
    <div class="dashboard-status-sec" style="background: #e1fcf8 ">
        <div class="row" style="margin: 0px">
            <div class="col-md-3"></div>
            <div class="col-md-6 p-4" style=" background:white; margin-top:100px; min-height: 400px; border-top: 2px solid #3d4c95">
                    <h3 class="">Account Exists</h3>
               <div class="p-5 text-left ">
                    <p class="mb-3">
                        <b>Hi {{ user.username }},</b>
                    </p><p class="">It seems that you have already created account with <b>{{ user.email }}</b>!
                        <br>
                       Kindly if you have not activated your account then click button to resend activation email to <b>{{ user.email }}</b>.

                    </p>
                    <div class="p-4"><button style="background: #3d4c95; border: 0px" class="btn btn-primary" onclick="ResendEmail()">Resend Email</button></div>

                   <div style="display: none;background: lightgreen" id="mailSend">Email is sent to {{ user.email }}</div>


               </div>

            </div>
            <div class="col-md-3"></div>
        </div>

    </div>
{% endblock %}


{% block script %}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
    function ResendEmail() {
        $.ajax({
            type: "GET",
            url: '/accounts/confirm_email_retry/{{ uid }}/{{ token }}',
            success: onResend,
            dataType: 'html'
        });
    }

    function onResend() {
        $('#mailSend').css('display','block')
        swal("Email Resent", "Email has sent to {{ user.email }}", "success");
    }
    </script>
{% endblock %}